spring:
    application:
        name: api

    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                auto_quote_keyword: true
                globally_quoted_identifiers: true
